### ISSUE TITLE
What is the status/roadmap of this crate

### ISSUE THREAD

**Issue by Hywan** [TomBebbington/llvm-rs#10]
Hello :-),

I am very interesting by the approach of this crate and I would like to use it. However, I wonder what is the status or the roadmap of this crate? Is it still maintained? Still active?

Thanks!

**Comment by TomBebbington** [comment]
I don't post updates often, but I am doing my best to actively maintain this crate. It's still active and the roadmap is pretty much to keep up to data with llvm-sys.
