### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by koromorix** [TomBebbington/llvm-rs#14]
I built LLVM from source today, so `llvm-config --version` is `3.9.0svn`.
(I also installed Rust today, so `cargo --version` is `cargo 0.7.0-nightly (1af03be 2015-12-08)` and `rustc --version` is `rustc 1.6.0 (c30b771ad 2016-01-19)`.)
I can use LLVM in c++ projects, but I can't use llvm-rs.
I cloned it and ran `cargo test`, resulting in:

	Compiling llvm-alt v0.3.2 (file:///home/koro/llvm-rs)
	error: linking with `cc` failed: exit code: 1
	note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/koro/llvm-rs/target/debug/examples/tan.0.o" "-o" "/home/koro/llvm-rs/target/debug/examples/tan" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/koro/llvm-rs/target/debug" "-L" "/home/koro/llvm-rs/target/debug/deps" "-L" "/usr/local/lib" "-L" "/home/koro/llvm-rs/target/debug/build/llvm-sys-911ba2de1be78b49/out" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/koro/llvm-rs/target/debug/libllvm.rlib" "/home/koro/llvm-rs/target/debug/deps/libllvm_sys-911ba2de1be78b49.rlib" "/home/koro/llvm-rs/target/debug/deps/libbitflags-7fb3e7f9e3d1842c.rlib" "/home/koro/llvm-rs/target/debug/deps/libcbox-e0efb99b7f89721a.rlib" "/home/koro/llvm-rs/target/debug/deps/liblibc-58e0bfb9440c5f8f.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-ca9f0d77.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-ca9f0d77.rlib" "-l" "rt" "-l" "dl" "-l" "pthread" "-l" "z" "-l" "m" "-l" "stdc++" "-l" "c" "-l" "m" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "compiler-rt"
	note: /home/koro/llvm-rs/target/debug/examples/tan.0.o: In function `cbox..CSemiBox$LT$llvm..module..Module$GT$::drop.4317::h57368b7cc4129623':
	tan.0.rs:(.text._ZN42cbox..CSemiBox$LT$llvm..module..Module$GT$9drop.431717h57368b7cc4129623E+0x5a): undefined reference to `LLVMDisposeModule'
	/home/koro/llvm-rs/target/debug/examples/tan.0.o: In function `cbox..CSemiBox$LT$llvm..builder..Builder$GT$::drop.4348::hd45b97f5c93d02d9':
	tan.0.rs:(.text._ZN44cbox..CSemiBox$LT$llvm..builder..Builder$GT$9drop.434817hd45b97f5c93d02d9E+0x5a): undefined reference to `LLVMDisposeBuilder'
	/home/koro/llvm-rs/target/debug/examples/tan.0.o: In function `tan::engine::ExecutionEngine::get_global<llvm::engine::JitEngine,u8>':
	/home/koro/llvm-rs/src/engine.rs:72: undefined reference to `LLVMGetPointerToGlobal'
	/home/koro/llvm-rs/target/debug/libllvm.rlib(llvm.0.o): In function `llvm::builder::Builder::new':
	/home/koro/llvm-rs/src/builder.rs:45: undefined reference to `LLVMCreateBuilderInContext'
	... skip a few ...
	collect2: error: ld returned 1 exit status

(I get similar "undefined reference" errors when trying to compile examples/fib.rs in a project with llvm-alt as a dependency.)

**Comment by TomBebbington** [comment]
Are all the LLVM libraries in a folder `ld` has been setup to search in for libraries?

Anyhow, this is a problem with the [llvm-sys](https://bitbucket.org/tari/llvm-sys.rs/) crate as that manages linking LLVM to the program. If this same problem persists, please file an issue on there instead.
